# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

FROM cs_webapi
MAINTAINER Alexander Blum <alexander.blum@c3s.cc>

# see api Dockerfile to enable winpdb debugging
