#!/bin/sh
# set -e

isCommand() {
    run "$1" --help > /dev/null 2>&1
}

SCRIPTNAME=$(basename -- "$0")

# docker-compose run commands
if [ "$SCRIPTNAME" = "entrypoint" ]; then
    # call of run explicitly
    if [ "$1" = "run" ]; then
        exec "$@"
    # call of a run subcommand
    elif isCommand "$1"; then
        run "$@"
    # other commands
    else
        exec "$@"
    fi
# docker-compose exec commands
elif isCommand "$SCRIPTNAME"; then
    run $SCRIPTNAME "$@"
# other commands
else
    exec "$@"
fi
