#!/bin/sh
# set -e

isCommand() {
    run "$1" --help > /dev/null 2>&1
}

SCRIPTNAME=$(basename -- "$0")

# docker-compose run commands
if [ "$SCRIPTNAME" = "entrypoint" ]; then
    # call of run explicitly
    [ "$1" = "run" ] && exec "$@"
    # call of a run subcommand
    isCommand "$1" && run "$@"
# docker-compose exec commands
elif isCommand "$SCRIPTNAME"; then
    run $SCRIPTNAME "$@"
# other commands
else
    exec "$@"
fi
