#!/bin/sh

isCommand() {
    execute "$1" --help > /dev/null 2>&1
}

# check if the first argument passed in looks like a flag
if [ "${1#-}" != "$1" ]; then
    execute "$@"
# check if the first argument passed in is a command
elif isCommand "$1"; then
    execute "$@"
# otherwise just execute the command
else
    exec "$@"
fi
