# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

networks:
  frontend:
  backend:

volumes:
  collecting_society_postgresql_data:
  collecting_society_echoprint_data:
  collecting_society_trytond_files:
  collecting_society_nginx_certs:
  collecting_society_nginx_dhparam:

services:

  database:
    restart: always
    networks:
      - backend
    volumes:
      - collecting_society_postgresql_data:/var/lib/postgresql/data

  erpserver:
    restart: always
    networks:
      - backend
    ports:
      - "8000:8000"  # jsonrpc (tryton client)
      - "8069:8069"  # xmlrpc (proteus)
    volumes:
      - collecting_society_trytond_files:/var/lib/trytond

  webserver:
    restart: always
    networks:
      - frontend
    ports:
      - "80:80"  # http
    volumes:
      - collecting_society_nginx_certs:/etc/nginx/certs
      - collecting_society_nginx_dhparam:/etc/nginx/dhparam

  webapi:
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - collecting_society_trytond_files:/var/lib/trytond

  webgui:
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - collecting_society_trytond_files:/var/lib/trytond

  worker:
    restart: always
    networks:
      - backend

  fingerprint:
    restart: always
    networks:
      - backend
    volumes:
      - collecting_society_echoprint_data:/opt/echoprint-data
