#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Healthcheck script for trytond

[ -f "running_db_creation.delete_me" ] && exit 0
! printf "" 2>>/dev/null >>/dev/tcp/127.0.0.1/$TRYTON_PORT && exit 1
exit 0
