#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Healthcheck script for echoprint
exit 0

if $WORKERPATH/test_connection.py; then
    exit 0
fi
exit 1
