#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Healthcheck script for echoprint

if [ $(netstat -tulpn | grep -P "(80|8502|1978)" | wc -l) = 3 ]; then
    exit 0
fi
exit 1
