#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Healthcheck script for pyramid

! printf "" 2>>/dev/null >>/dev/tcp/127.0.0.1/$VIRTUAL_PORT && exit 1
exit 0
