#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Healthcheck script for ngninx

if service nginx status; then
    exit 0
fi
exit 1
