#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Healthcheck script for worker

[ -f "running_db_creation.delete_me" ] && exit 0
! $WORKDIR/src/collecting_society_worker/collecting_society_worker/test_connection.py && exit 1
exit 0
