# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/c3s.ado.repertoire

FROM c3s_repertoire_api
MAINTAINER Udo Spallek <udono@virtual-things.biz>

# see api Dockerfile to enable winpdb debugging