# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/c3s.ado.repertoire

FROM postgres:9.4
MAINTAINER Udo Spallek <udono@virtual-things.biz>
