#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Deploy script for trytond

DEV=""
if [ "$ENVIRONMENT" = "development" ] || [ "$ENVIRONMENT" = "staging" ]; then
    DEV="--dev"
fi

trytond $DEV -c $WORKDIR/config/trytond/$ENVIRONMENT.conf
