#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Usage: ./up

PROJECT="collecting_society"

# get directories
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$( dirname $SCRIPT_DIR )"
SHARED_DIR=$ROOT_DIR/volumes/shared

# start docker
if ! [ `systemctl is-active docker` = "active" ]; then
    echo "Start docker ..."
    sudo systemctl start docker
fi

# start tmux session
echo "Start tmux session ..."
tmux has-session -t $PROJECT &> /dev/null
if [ $? != 0 ]; then
    # logs
    tmux new-session -s $PROJECT -n logs -c $ROOT_DIR -d
    tmux send-keys -t $PROJECT "docker-compose up" C-m
    # collecting_society_docker
    tmux new-window -a -t $PROJECT -n collecting_society_docker -c $ROOT_DIR
    tmux send-keys -t $PROJECT "git status" C-m
    # portal
    tmux new-window -a -t $PROJECT -n portal -c $SHARED_DIR/src/portal
    tmux send-keys -t $PROJECT "git status" C-m
    # collecting_society
    tmux new-window -a -t $PROJECT -n collecting_society -c $SHARED_DIR/src/collecting_society
    tmux send-keys -t $PROJECT "git status" C-m
    # portal_web
    tmux new-window -a -t $PROJECT -n portal_web -c $SHARED_DIR/src/portal_web
    tmux send-keys -t $PROJECT "git status" C-m
    # collecting_society_web
    tmux new-window -a -t $PROJECT -n collecting_society_web -c $SHARED_DIR/src/collecting_society_web
    tmux send-keys -t $PROJECT "git status" C-m
    # select active window
    tmux select-window -t $PROJECT:logs
fi

# start firefox
if command -v firefox > /dev/null; then
    echo -n "Wait for container to start ..."
    while [ -z `docker ps -q --no-trunc | grep $(docker-compose ps -q webgui)` ]; do
        sleep 1
        echo -n "."
    done
    echo -e "\nStart firefox ..."
    firefox "https://redmine.c3s.cc/login?back_url=https%3A%2F%2Fredmine.c3s.cc%2Fprojects%2F$PROJECT" &
    firefox "http://$PROJECT.test:81" &
fi

# attach to tmux session
echo "Attach to tmux session ..."
tmux attach -t $PROJECT
