#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Usage: ./test [service] [--down] [--build] [--keep] [--ci] [OTHER PARARAMS]
#
# Options:
#     service: web|worker|all (default: all)
#     --down: immediately stop and remove the container and exit
#     --build: build images and recreate the test database template
#     --keep: keep container running
#     --ci: continous integration mode
#           - update repositories (overrides config files!)
#           - build images
#           - recreate the test database template
#           - stop and remove the container
#     OTHER PARAMS: are passed to run-tests within the container

echo "====================================================================="
echo "====================================================================="
echo "= this script stops, updates, builds and tests the docker setup     ="
echo "====================================================================="
echo `date +%Y-%m-%d:%H:%M:%S`

# get directories
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$( dirname $SCRIPT_DIR )"
cd $ROOT_DIR

# get options
SERVICE="all"
BUILD=false
RM=true
CI=false
DOWN=false
TESTPARAMS=""
for i in "$@"; do
    if [ $i = $1 ] && ([ $i = "erpserver" ] || [ $i = "web" ] || [ $i = "worker" ]);
        then SERVICE=$i; continue; fi
    if [ $i = "--down" ]; then DOWN=true; continue; fi
    if [ $i = "--build" ]; then BUILD=true; continue; fi
    if [ $i = "--keep" ]; then RM=false; continue; fi
    if [ $i = "--ci" ]; then CI=true; continue; fi
    TESTPARAMS="$TESTPARAMS $i"
done

# sanity checks
if [ $SERVICE != "all" ] && [ $SERVICE != "erpserver" ] && [ $SERVICE != "web" ] && [ $SERVICE != "worker" ]; then
    echo "Service unknown. Please specify 'web' or 'worker'"
    exit -1
fi

# use testing compose file
TESTING="-f docker-compose.testing.yml"

# immediately stop and remove the container and exit
if $DOWN; then
    echo -e "\n== immediately stop and remove the container and exit"
    docker-compose $TESTING down
    exit $?
fi

# update repositories
if $CI; then
    echo -e "\n== update repositories"
    $SCRIPT_DIR/update --reset
fi

# build docker images
if $CI || $BUILD; then
    echo -e "\n== build images"
    docker-compose $TESTING build
fi

# create and start docker container
echo -e "\n== create and start docker container"
docker-compose $TESTING up -d
if [ $? -ne 0 ]; then
    echo -e "\n... if the images are missing or need to be updated, use './test --build'"
fi

# recreate test database template
if $CI || $BUILD; then
    echo -e "\n== recreate test database template"
    docker-compose $TESTING exec -T test_erpserver execute create-test-db
fi

# run tests
echo -e "\n== run tests"
if [ $SERVICE = "all" ]; then
    # test web service
    echo -e "\n... run erpserver tests"
    docker-compose $TESTING exec -T test_erpserver execute run-tests erpserver $TESTPARAMS
    EXITCODE1=$?
    # test web service
    echo -e "\n... run web tests"
    docker-compose $TESTING exec -T test_web execute run-tests web $TESTPARAMS
    EXITCODE2=$?
    # test worker service
    echo -e "\n... run worker tests"
    docker-compose $TESTING exec -T test_worker execute run-tests worker $TESTPARAMS
    EXITCODE3=$?
    # choose exit code
    EXITCODE=0
    if [ "$EXITCODE1" -ne "0" ] || [ "$EXITCODE2" -ne "0" ] || [ "$EXITCODE3" -ne "0" ]; then
        EXITCODE=-1
    fi
else
    # test certain service
    docker-compose $TESTING exec -T test_$SERVICE execute run-tests $SERVICE $TESTPARAMS
    EXITCODE=$?
fi

# remove docker container
if $CI || $RM; then
    echo -e "\n== remove docker container"
    docker-compose $TESTING rm -fs
fi

if [ "$EXITCODE" -ne "0" ]; then
    echo -e "\n\n\033[91;5m"
    echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
    echo -e " WARNING: ERRORS OCCURED WHILE TESTS WERE RUNNING. PLEASE FIX.\n"
    echo -e "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
    echo -e "\033[0m"
fi
echo `date +%Y-%m-%d:%H:%M:%S`
echo "====================================================================="
echo "====================================================================="

exit $EXITCODE
