#!/bin/bash
# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker
#
# Usage: ./test [--down] [--build] [--keep] [--ci] [OTHER PARARAMS]
#
# Options:
#     --down: immediately stop and remove the container and exit
#     --build: build images
#     --keep: keep container running
#     --ci: continous integration mode
#           - update repositories (overrides config files!)
#           - build images
#           - recreate the test database template
#           - stop and remove the container
#     OTHER PARAMS: are passed to run-tests within the container

echo "====================================================================="
echo "====================================================================="
echo "= this script stops, updates, builds and tests the docker setup     ="
echo "====================================================================="
echo `date +%Y-%m-%d:%H:%M:%S`

# get directories
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$( dirname $SCRIPT_DIR )"
cd $ROOT_DIR

# get options
BUILD=false
RM=true
CI=false
DOWN=false
TESTPARAMS=""
for i in "$@"; do
    if [ $i = "--down" ]; then DOWN=true; continue; fi
    if [ $i = "--build" ]; then BUILD=true; continue; fi
    if [ $i = "--keep" ]; then RM=false; continue; fi
    if [ $i = "--ci" ]; then CI=true; continue; fi
    TESTPARAMS="$TESTPARAMS $i"
done

# use testing compose file
TESTING="-f docker-compose.testing.yml"

# immediately stop and remove the container and exit
if $DOWN; then
    echo -e "\n== immediately stop and remove the container and exit"
    docker-compose $TESTING down
    exit $?
fi

# update repositories
if $CI; then
    echo -e "\n== update repositories"
    $SCRIPT_DIR/update --reset
fi

# build docker images
if $CI || $BUILD; then
    echo -e "\n== build images"
    docker-compose $TESTING build
fi

# create and start docker container
echo -e "\n== create and start docker container"
docker-compose $TESTING up -d
if [ $? -ne 0 ]; then
    echo -e "\n... if the images are missing, use './test --build'"
fi

# recreate test database template
if $CI; then
    echo -e "\n== recreate test database template"
    docker-compose $TESTING exec test_web execute create-test-db
fi

# run tests
echo -e "\n== run tests"
docker-compose $TESTING exec test_web execute run-tests $TESTPARAMS
EXITCODE=$?

# remove docker container
if $CI || $RM; then
    echo -e "\n== remove docker container"
    docker-compose $TESTING rm -fs
fi

echo `date +%Y-%m-%d:%H:%M:%S`
echo "====================================================================="
echo "====================================================================="

exit $EXITCODE
